### ISSUE TITLE
Update to v5.0 leads to require error

### ISSUE THREAD

**Issue by TheFive** [kpdecker/jsdiff#308]
After update to V5.0 loading diff module fails:

```
Error: Package exports for '/Users/TheFive.osm/development/osmbc/node_modules/diff' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/TheFive.osm/development/osmbc/model/logModule.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND'
}
```
logModule.js row 9 contains the require("diff") statement.

Node Version v13.1.0
npm version 6.14.8

Christoph

**Comment by TheFive** [comment]
Sorry, this was a node v13.1.0 problem.
Update to v14 solves the issue.

I should not install non LTS versions of node.
